// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCytG9UNjtb4Nf8YStJQuGbnz6rDjjp9ps',
    appId: '1:345005927248:web:503843401be3a152729a55',
    messagingSenderId: '345005927248',
    projectId: 'basic-view-task-01',
    authDomain: 'basic-view-task-01.firebaseapp.com',
    storageBucket: 'basic-view-task-01.appspot.com',
    measurementId: 'G-Y459FYJ1SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9yyEPF0bTLsjE1OxhNRMSKeflvNpzS8',
    appId: '1:345005927248:android:6f100ceb882f9f07729a55',
    messagingSenderId: '345005927248',
    projectId: 'basic-view-task-01',
    storageBucket: 'basic-view-task-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1jL2y1leHp2DQ8irxYrEGl_mTHaVK4s',
    appId: '1:345005927248:ios:0111230a69688de6729a55',
    messagingSenderId: '345005927248',
    projectId: 'basic-view-task-01',
    storageBucket: 'basic-view-task-01.appspot.com',
    iosBundleId: 'com.example.basicViewTaks1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR1jL2y1leHp2DQ8irxYrEGl_mTHaVK4s',
    appId: '1:345005927248:ios:482084eb4d75a2de729a55',
    messagingSenderId: '345005927248',
    projectId: 'basic-view-task-01',
    storageBucket: 'basic-view-task-01.appspot.com',
    iosBundleId: 'com.example.basicViewTaks1.RunnerTests',
  );
}
